Web_VideoEditing/Web_VideoEditing/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("users/",include('users.urls')),
    path("", include('clients.urls')),
    path("administrators/", include('administrators.urls')),
    path("", include('user_project.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Web_VideoEditing/administrators/urls.py
from django.urls import path, include
from . import views
urlpatterns = [
    path('', views.index_admin, name="index_admin"),
    path('detail_user', views.detail_user, name="detail_user"),
    
]

Web_VideoEditing/clients/urls.py
from django.urls import path, include
from .import views

app_name = 'clients'
urlpatterns = [
    path('', views.home, name="home"),
    path('all_tools/', views.all_tools, name="all_tools"),
    path('add_subtitles/', views.add_subtitles, name="add_subtitles"),
    path('merge_video/', views.merge_video, name="merge_video"),
    path('merge_tools/', views.merge_tools, name="merge_tools"),
    path('crop_video/', views.crop_video, name="crop_video"),
    path('crop_tool/', views.crop_tool, name="crop_tool"),
    path('cut_tool/', views.cut_tool, name="cut_tool"),
    path('cut_video/', views.cut_video, name="cut_video"),
    path('loop_video/', views.loop_video, name="loop_video"),
    path('loop_tool/', views.loop_tool, name="loop_tool"),

]

Web_VideoEditing/user_project/urls.py
from django.urls import path
from .import views

app_name = 'user_project'
urlpatterns = [
    path('index', views.home, name="index"),
]

Web_VideoEditing/users/urls.py
from django.urls import path, include
from . import views
app_name = 'users'
urlpatterns = [
    # path('', views.home, name="home"),
    path('signup/', views.signup, name="signup"),
    path('signin/', views.signin, name="signin"),
    path('signout/', views.signout, name="signout"),
]

Web_VideoEditing/administrators/models.py
from django.db import models

# Create your models here.

Web_VideoEditing/clients/models.py
from django.db import models
from users.models import Users

# Create your models here.
class Subtitle(models.Model):
    path = models.FileField(upload_to='audio_files/')
    name = models.CharField(max_length=100)
    
    class Meta:
        db_table = "Subtitle"

class Upload(models.Model):
    path_video = models.FileField(upload_to='Files/')
    title_video = models.CharField(max_length=200, null=True)
    path_image = models.FileField(upload_to='Files/', null=True)
    
    class Meta:
        db_table = "Upload"


class UserUpload(models.Model):
    user = models.ForeignKey(Users, on_delete=models.CASCADE)
    upload = models.ForeignKey(Upload, on_delete=models.CASCADE)
    
    class Meta:
        db_table = "UserUpload"
    
class Video(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    video_edit = models.FileField(upload_to='video_edits/')
    duration = models.IntegerField()
    format = models.CharField(max_length=50)
    size = models.IntegerField()
    update_date = models.DateTimeField()
    thumb = models.ImageField(upload_to='video_thumbs/')
    user_id = models.ForeignKey(Users, on_delete=models.CASCADE)
    subtitle_id = models.ForeignKey(Subtitle, on_delete=models.CASCADE)
    upload_id = models.ForeignKey(Upload, on_delete=models.CASCADE)
    
    class Meta:
        db_table = "Video"

Web_VideoEditing/user_project/models.py
from django.db import models

# Create your models here.

Web_VideoEditing/users/models.py
from django.db import models
from django.utils import timezone
from PIL import Image


# Create your models here.
class Users(models.Model):
    username = models.CharField(max_length=100)
    email = models.EmailField()
    password = models.CharField(max_length=20)
    create_at = models.DateTimeField(default=timezone.now)
    role = models.CharField(max_length=50, default='client')
    image = models.ImageField(default='default.jpg', upload_to='profile_pics/')
    
    class Meta:
        db_table = "users"
        
    def __str__(self):
        return self.username

    def save(self, *args, **kwargs):
        super(Users, self).save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)
    

Web_VideoEditing/clients/forms.py
from django import forms
from .models import Upload

class FileUploadForm(forms.ModelForm):
    class Meta:
        model = Upload
        fields = ['path_video']

Web_VideoEditing/administrators/views.py
from django.shortcuts import render

# Create your views here.
def index_admin(request):
    return render(request, 'administrators/index_admin.html')

def detail_user(request):
    return render(request, 'administrators/detail_user.html')

Web_VideoEditing/clients/views.py
from django.shortcuts import render
from users.models import Users
from django.http import HttpResponse
import os
from django.conf import settings
from .forms import FileUploadForm

def base_context(request):
    username = request.session.get('username', None)
    user_profile = Users.objects.get(username=username) if username else None
    return {'user_profile': user_profile}

def home(request):
    context = base_context(request)
    return render(request, 'clients/index.html', context)

def all_tools(request):
    context = base_context(request)
    return render(request, 'clients/all_tools.html', context)


def add_subtitles(request):
    return render(request, 'clients/add_subtitles.html')

def merge_video(request):
    context = base_context(request)
    return render(request, 'clients/merge_video.html', context)

def merge_tools(request):
    return render(request, 'clients/merge_tools.html')

def crop_video(request):
    context = base_context(request)
    return render(request, 'clients/crop_video.html', context)

def crop_tool(request):
    return render(request, 'clients/crop_tool.html')

def cut_video(request):
    if request.method == "POST":
        form = FileUploadForm(request.POST, request.FILES)
        dd(form.is_valid())
        if form.is_valid():
            dd(form)
    else:
        form = FileUploadForm()
        
    context = base_context(request)
    return render(request, 'clients/cut_video.html', context)

def cut_tool(request):
    return render(request, 'clients/cut_tool.html')

def loop_video(request):
    context = base_context(request)
    return render(request, 'clients/loop_video.html', context)

def loop_tool(request):
    return render(request, 'clients/loop_tool.html')

Web_VideoEditing/user_project/views.py
from django.shortcuts import render
from users.models import Users
from django.http import HttpResponse
# Create your views here.
def base_context(request):
    username = request.session.get('username', None)
    user_profile = Users.objects.get(username=username) if username else None
    return {'user_profile': user_profile}

def home(request):
    context = base_context(request)
    return render(request, 'user_project/index.html', context)

Web_VideoEditing/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.http import HttpResponse, HttpResponseBadRequest
from django.contrib.auth.models import User
from django.contrib import messages
from .models import Users

def signup(request):
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        mysqluser = Users(username=username, email=email, password=password)
        mysqluser.save()
        return redirect('users:signin')
    
    
    return render(request, 'users/signup.html')

def signin(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        
        try:
            user = Users.objects.get(email=email, password=password)
            if user is not None:
                request.session['username'] = user.username
                return redirect('clients:home')
            else:
                print("Some tried to login and failed")
                print("They used email: {} and password: {}".format(email, password))
                
                return redirect('/')
        except Users.DoesNotExist:
            print("User does not exist")
            return redirect("/")
    
    return render(request, 'users/signin.html')
    
def signout(request):
    logout(request)
    return redirect('clients:home')

Web_VideoEditing/administrators/templates/administrators/detail_user.html
 {% extends "administrators/base_admin.html" %} {% block content %}
<div class="container">
    <div>
        <h3>User - NgocAnh</h3>
    </div>
    <div class="main1">
        <div class="container">
            <div class="row">
                <div class="col-sm" style="position: relative;height: 225px;width: 225px">
                    {% load static %}
                    <img src="{% static 'administrators/images/1.PNG' %} " alt=" " class="image1 " style="height: 225px;width: 225px;display: block; ">
                    <i class="fa-solid fa-ellipsis-vertical" style=" position: absolute;top: 12%; left: 60%;transform: translate;z-index: 1;font-weight: bold;font-size: 20px;color:#fff"></i>
                    <p style=" position: absolute;top: 10%; left: 7%;transform: translate;z-index: 1;font-weight: bold;font-size: 20px;color:#fff ">Sun_video</p>
                    <p style=" position: absolute;top: 88%; left: 5%;transform: translate;z-index: 1;font-weight: bold;font-size: 14px;color:#fff ">00:13</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

Web_VideoEditing/clients/templates/clients/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="initial-scale=1, width=device-width" />
    <link rel="stylesheet" href="{% static 'clients/css/global.css' %}"/>
    <link rel="stylesheet" href="{% static 'clients/css/base.css' %}"/>
    {% block stylesheets %}

    {% endblock stylesheets %}
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;400;500;600&display=swap" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Google Sans:wght@500&display=swap" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Volkhov:wght@700&display=swap" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Lexend:wght@400;600&display=swap" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" />
  </head>

  <body>
    <div class="nav">
        <div class="edit-video"><a href="{% url 'clients:home' %}">Edit video</a></div>
        <div class="dropdown">
          <button class="dropdown-toggle" type="button" data-bs-toggle="dropdown">
            Tools
          </button>
          <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'clients:loop_video'%}">Loop video</a></li>
              <li><a class="dropdown-item" href="{% url 'clients:merge_video'%}">Merge video</a></li>
              <li><a class="dropdown-item" href="{% url 'clients:cut_video'%}">Cut video</a></li>
              <li><a class="dropdown-item" href="{% url 'clients:crop_video'%}">Crop video</a></li>
              <li><hr class="dropdown-divider" /></li>
              <li><a class="dropdown-item" href="{% url 'clients:all_tools' %}">All tools<i class="fa-solid fa-chevron-right"></i></a></li>
          </ul>
        </div>
        <div class="resources">Resources</div>
        
        {% if user_profile %}
        <div class="dropdown1">
          <img src="{{ user_profile.image.url }}" class="dropbtn"/>
          <div class="dropdown-content">
          <a href="#">{{ user_profile.username }}</a>
          <a href="{% url 'users:signout' %}">Log out</a>
          </div>
        </div>
        {% else %}
        <div class="sign-in-wrapper">
          <div class="sign-in">
            <a href="{% url 'users:signin'%}">Sign in</a>
          </div>
        </div>
        {% endif %}
      </div>

    {% block content %}
      
    {% endblock  %}
      
    <div class="footer">
        <div class="footer-child"></div>
        <div class="features-parent">
          <div class="features">Features</div>
          <div class="our-features">Our Features</div>
          <div class="pricing">Pricing</div>
          <div class="affiliate-program">Affiliate Program</div>
          <div class="press-kit">Press Kit</div>
        </div>
        <div class="support-parent">
          <div class="features">Support</div>
          <div class="account">Account</div>
          <div class="help">Help</div>
          <div class="contact-us">Contact Us</div>
        </div>
        <div class="legal-parent">
          <div class="legal">Legal</div>
          <div class="privacy-policy">Privacy Policy</div>
          <div class="terms-of-use">Terms of Use</div>
        </div>
        <div class="social-media-parent">
          <div class="social-media">Social Media</div>
          <div class="twitter">Twitter</div>
          <div class="product-hunt">Product Hunt</div>
          <div class="instagram">Instagram</div>
          <div class="github">Github</div>
        </div>
        <div class="copyright-2023-editvideo">Copyright 2023 @editvideo</div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
  </body>
</html>

Web_VideoEditing/clients/templates/clients/cut_video.html
{% extends "clients/base.html" %} {% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% block stylesheets %}
      {{ block.super }}
      <link rel="stylesheet" type="text/css" href="{% static 'clients/css/global.css' %}" />
      <link rel="stylesheet" type="text/css" href="{% static 'clients/css/cut_video.css' %}" />
    {% endblock stylesheets %}
</head>

<body>
    {% block content %}
    <div class="cutp-video">
      <div class="gr1">
        <b class="heading"><p class="video-cutter-online">Video Cutter Online</p></b>
        <div class="desc">Trim the necessary part of your video</div>
{% comment %} 
        <div class="upload-wrapper">
          <button type="submit" class="cta6">Upload</button>
        </div>
        <div class="choose-file-parent">
          <button type="submit" class="choosefile">Choose file
            <img class="add-1-icon1" alt="" src="{% static 'clients/images/add-1@2x.png' %}" />
          </button>
        </div> {% endcomment %}

        <form method="post" action="{% url 'clients:cut_video' %}" enctype="multipart/form-data" class="c_file">
          {% csrf_token %}
          Choose file: <input class="c_file" type="file" name="video_file" id="video_file">
          <button type="submit" class="cta6">Submit</button>
       </form>

        
      </div>

      <div class="gr2">
        <div class="card">
          <div class="base"></div>
          <div class="fast-video-cutting-container"><p class="video-cutter-online">Fast Video Cutting</p> </div>
          <img class="card-child" alt="" src="{% static 'clients/images/frame-427319047@2x.png' %}"/>
          <div class="the-tool-allows"> The tool allows you to move the two markers to select the beginning and ending of your clip. It takes just a few seconds! </div>
        </div>

        <div class="card1">
          <div class="base"></div>
          <div class="completely-online">Completely Online</div>
          <div class="you-dont-need"> You don't need to download or install anything on your device, that is not only faster but also more secure.</div>
          <img class="card-item" alt="" src="{% static 'clients/images/frame-427319049@2x.png' %}" />
        </div>

        <div class="card2">
          <div class="base"></div>
          <div class="completely-online">Easy-to-use</div>
          <img class="card-child" alt="" src="{% static 'clients/images/frame-427319047@2x.png' %}"/>
          <div class="you-dont-need-container">
            <p class="video-cutter-online">You don't need any experience in video editing to use the online service because its interface is intuitive. </p>
          </div>
        </div>
      </div>

      <div class="gr3">
        <img class="image-47-icon" alt="" src="{% static 'clients/images/image-47@2x.png' %}" />
        <b class="how-to-cut">How to cut a video online</b>
        <div class="step-3"> <div class="step-3-save">Step 3: Save the result</div> </div>
        <div class="step-2"> <div class="step-3-save">Step 2: Create a video</div> </div>
        <div class="step-1">
          <div class="step-1-upload-a-recording-or-parent">
            <div class="step-3-save">Step 1: Upload a recording or movie</div>
            <div class="add-a-video"> Add a video to the subtitler: from your computer, a camera roll on your smartphone, or from a cloud. The tool accepts 500 MB for free </div>
          </div>
        </div>
      </div>

      <div class="contact">
        <img class="image-45-icon" alt="" src="{% static 'clients/images/image-45@2x.png' %}" />
        <div class="contact-bt">
          <div class="contact-bt-child"></div>
          <div class="insert-your-email">Insert your email address</div>
          <img class="send-icon" alt="" src="{% static 'clients/images/send@2x.png' %}" />
        </div>

        <div class="have-a-too-container">
          <p class="video-cutter-online"> Have a too large file for uploading to Instagram, Facebook, YouTube, or for sending via Email? It's not a problem anymore, with our tool you can easily make your video smaller without losing quality! </p>
          <p class="video-cutter-online"> Clideo's interface is user-friendly so you don't need to have any special video editing skills to use it! </p>
          <p class="video-cutter-online">&nbsp;</p>
          <p class="video-cutter-online"> Contact us if you are interested in working with us </p>
        </div>
      </div>
    </div>

    {% endblock content %}

</body>

</html>

Web_VideoEditing/clients/templates/clients/index.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="initial-scale=1, width=device-width" />
    <link rel="stylesheet" href="{% static 'clients/css/global.css' %}" />
    <link rel="stylesheet" href="{% static 'clients/css/index.css' %}" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@500&display=swap" />
</head>
<body>
    <div class="index1">

    <div class="nav">
        <img class="pexels-jessica-lewis-593324-2-icon" alt="" src="{% static 'clients/images/pexelsjessicalewis593324-2@2x.png' %}" />
        <div class="edit-video">Edit video</div>
        <div class="resources">Resources</div>
        {% if user_profile %}
        <div class="dropdown1">
          <img src="{{ user_profile.image.url }}" class="dropbtn"/>
          <div class="dropdown-content">
          <a href="#">{{ user_profile.username }}</a>
          <a href="#">Log out</a>
          </div>
        </div>
        {% else %}
        <div class="sign-in-wrapper">
          <div class="sign-in">
            <a href="{% url 'users:signin'%}">Sign in</a>
          </div>
        </div>
        {% endif %}
    </div>

    <div class="slide">
        <div class="make-your-interior"> Make Your Interior More Minimaistic & Modern </div>
        <div class="all-in-one-easy-to-use-online"> All-in-one easy-to-use online video tools </div>
        <div class="search-column">
            <div class="search-column-child"></div>
            <div class="search">Search</div>
            <img class="button-search-icon" alt="" src="{% static 'clients/images/button-search@2x.png' %}" />
        </div>
    </div>

    <div class="reason">
        <div class="rectangle-parent">
            <div class="group-child"></div>
            <div class="there-is-no"> There is no need to download and install any app to your phone, tablet or computer — use the online Clideo tools instead. </div>
            <div class="completely-online"><p class="why">Completely Online</p> </div>
        </div>
        <div class="rectangle-group">
            <div class="group-item"></div>
            <div class="kapwing-is-completely"> Kapwing is completely free to start. Just upload a video and start editing. Supercharge your editing workflow with our powerful online tools. </div>
            <div class="free"> <p class="why">Free</p> </div>
        </div>
        <div class="rectangle-container">
            <div class="group-item"></div>
            <div class="kapwing-works-hard">Kapwing works hard to help make the content you want, when you want it. Get started on your project today. </div>
            <div class="powerful"><p class="why">Powerful</p> </div>
        </div>
        <div class="why-choosing-us-container">
            <p class="why">Why</p>
            <p class="why">Choosing Us</p>
        </div>
    </div>

    <div class="tool">
        <div class="online-video-tools">Online Video Tools</div>
        <div class="next">
            <div class="all-tools"><a href="{% url 'clients:all_tools'%}">All tools</a></div>
            <img class="next-child" alt="" src="{% static 'clients/images/arrow-2@2x.png' %}" />
        </div>
        <div class="tool4">
            <div class="tool4-child"></div>
            <div class="merge">Merge</div>
            <img class="merged-1-icon" alt="" src="{% static 'clients/images/merged-1@2x.png' %}" />
        </div>
        <div class="tool3">
            <div class="tool4-child"></div>
            <div class="cut">Cut</div>
            <img class="cutting-tool-1-icon" alt="" src="{% static 'clients/images/cuttingtool-1@2x.png' %}" />
        </div>
        <div class="tool2">
            <div class="tool4-child"></div>
            <div class="loop">Loop</div>
            <img class="loop-1-icon" alt="" src="{% static 'clients/images/loop-1@2x.png' %}" />
        </div>
        <div class="tool1">
            <div class="tool4-child"></div>
            <div class="crop">Crop</div>
            <img class="crop-1-icon" alt="" src="{% static 'clients/images/crop-1@2x.png' %}" />
        </div>
    </div>

    <div class="about">
        <div class="your-all-in-one-online"> Your all-in-one online video editor </div>
        <div class="make-your-own"> Make your own video from scratch, edit it and add music — all in one screen! Our seamless video editor allows you to manage the added media easily with the help of a multi-track timeline. </div>
        <img class="unsplashtqpypka92k8-icon" alt="" src="{% static 'clients/images/unsplashtqpypka92k8@2x.png' %}" />
    </div>

    <div class="footer">
        <div class="footer-child"></div>
        <div class="features-parent">
            <div class="features">Features</div>
            <div class="our-features">Our Features</div>
            <div class="pricing">Pricing</div>
            <div class="affiliate-program">Affiliate Program</div>
            <div class="press-kit">Press Kit</div>
        </div>
        <div class="support-parent">
            <div class="features">Support</div>
            <div class="account">Account</div>
            <div class="help">Help</div>
            <div class="contact-us">Contact Us</div>
        </div>
        <div class="legal-parent">
            <div class="legal">Legal</div>
            <div class="privacy-policy">Privacy Policy</div>
            <div class="terms-of-use">Terms of Use</div>
        </div>
        <div class="social-media-parent">
            <div class="social-media">Social Media</div>
            <div class="twitter">Twitter</div>
            <div class="product-hunt">Product Hunt</div>
            <div class="instagram">Instagram</div>
            <div class="github">Github</div>
        </div>
        <div class="copyright-2023-editvideo">Copyright 2023 @editvideo</div>
    </div>

    </div>
</body>
</html>

Web_VideoEditing/user_project/templates/user_project/index.html
{% extends "user_project/base.html" %}
{% block content %}
    <h1>Website chỉnh sửa Video</h1>
    {% if username %}
        <p>Welcome, {{ username }}!</p>
    {% else %}
        <p>Welcome, Guest!</p>
    {% endif %}
{% endblock content %}

</body>

</html>

Web_VideoEditing/users/templates/users/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Trang chủ</title>
</head>

<body>
    <h1>Website chỉnh sửa Video</h1>
    {% if username %}
        <p>Welcome, {{ username }}!</p>
    {% else %}
        <p>Welcome, Guest!</p>
    {% endif %}
</body>

</html>

Web_VideoEditing/users/templates/users/signin.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="initial-scale=1, width=device-width" />

    <link rel="stylesheet" href="{% static 'users/css/signin.css' %}">
    <link rel="stylesheet" href="{% static 'users/css/global.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700&display=swap" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Google Sans:wght@500&display=swap" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Volkhov:wght@700&display=swap" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400&display=swap" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Open Sans:wght@400;600&display=swap" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Lexend:wght@400;600&display=swap" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@500&display=swap" />
</head>

<body>
    <form action="{% url 'users:signin'%}" method='POST'>
        {% csrf_token %}
        <div class="login">
            <div class="frame-parent5">
                <div class="group-child61"></div>
                <div class="enter-your-credentials">
                    Enter your Credentials to access your account
                </div>
                <div class="frame-parent6">
                    <div class="password-frame">
                        <div class="name5">Name</div>
                    </div>
                    <div class="frame-child3"></div>
                </div>
                <div class="frame-parent7">
                    <div class="password-frame">
                        <div class="name5">Email address</div>
                    </div>
                    <div class="frame-wrapper5">
                        <div class="name-wrapper5">
                            <div class="name5">Enter your email</div>
                        </div>
                    </div>
                </div>
                <div class="frame-parent8">
                    <div class="password-frame">
                        <div class="name5">Password</div>
                    </div>
                    <div class="frame-wrapper5">
                        <div class="name-wrapper5">
                            <div class="name5">Name</div>
                        </div>
                    </div>
                </div>
                <div class="remember-for-30-days-parent">
                    <div class="remember-for-30">Remember for 30 days</div>
                    <div class="group-child62"></div>
                </div>
                <div class="group-wrapper1" id="frameContainer10">
                    <div class="dont-have-an-account-sign-up-wrapper">
                        <div class="dont-have-an-container1">
                            <span>Don’t have an account? </span>
                            <span><a class="sign-up2" href="{% url 'users:signup'%}">Sign Up</a></span>
                        </div>
                    </div>
                </div>
                <div class="frame-parent9">
                    <div class="frame-wrapper7">
                        <div class="ico<ns8-google-1-group">
                            <img class="icons8-google-11" alt="" src="{% static 'users/images/icons8google-1.svg' %}" />

                            <div class="name5">Sign in with Google</div>
                        </div>
                    </div>
                    <div class="frame-wrapper8">
                        <div class="icons8-apple-logo-1-group">
                            <img class="icons8-google-11" alt="" src="{% static 'users/images/icons8applelogo-1.svg' %}" />

                            <div class="name5">Sign in with Apple</div>
                        </div>
                    </div>
                </div>
                <div class="forgot-password">forgot password</div>
            </div>
            <div class="line-group">
                <div class="frame-child4"></div>
                <div class="or-container">
                    <div class="name5">Or</div>
                </div>
            </div>
            <div class="login-inner">
                <div class="rectangle-parent36">
                    <input class="group-child" type="text" id="email" name="email" placeholder="Enter your email" required>
                </div>
            </div>
            <div class="login-child">
                <div class="rectangle-parent36">
                    <input class="group-child" type="password" id="password" name="password" placeholder="Enter your password" required>
                </div>
            </div>
            <div class="rectangle-parent37">
                <button type="submit" class="login1">Sign In</button>
            </div>
            <div class="line-container">
                <div class="frame-child5"></div>
                <div class="or-frame">
                    <div class="name5">Or</div>
                </div>
            </div>
            <div class="welcome-back">Welcome back!</div>
            <img class="chris-lee-70l1tdai6rm-unsplash-icon1" alt="" src="{% static 'users/images/chrislee70l1tdai6rmunsplash-3@2x.png' %}" />
        </div>
    </form>
</body>

</html>